### PR TITLE
What's the reason for using `serialize()` and `json_encode()` to calculate the cache key?

### PR DESCRIPTION
**Pull request by jdreesen**
Wouldn't just using one of them be sufficient? I'm curious for the reason of using both.

### CODE REVIEW

**Comment by drupol** [comment]
Hello,

I'm using it because [json_encode()](https://www.php.net/manual/en/function.json-encode.php) might return `false` if it cannot encode the value.

And the tests are catching the issue :-)

**Comment by jdreesen** [comment]
Thanks for the explanation, but wouldn't that mean all closures where this happens would be cached with the same key: `e9d186a11303ede3bdf2431bfa7a5bbcd5a1a9eb` (the return value of `sha1(serialize(false))`)? Is this the correct behavior?

**Comment by jdreesen** [comment]
Probably just using `serialize` then would be sufficient. I see no value in double-encoding the arguments before hashing it.

**Comment by drupol** [comment]
> Thanks for the explanation, but wouldn't that mean all closures where this happens would be cached with the same key?

Yes indeed... because if we cannot json_encode the arguments, then we cannot memoize the closure.

**Comment by drupol** [comment]
> Probably just using `serialize` then would be sufficient. I see no value in double-encoding the arguments before hashing it.

Let me think about it and I'll come back at you!

**Comment by jdreesen** [comment]
That sounds reasonable... but maybe an exception should be thrown in this case?

**Comment by drupol** [comment]
> That sounds reasonable... but maybe an exception should be thrown in this case?

Could be, why not. This idea was to keep it very simple and fast.

**Comment by jdreesen** [comment]
> Let me think about it and I'll come back at you!

Take your time, I'm curious about the answer :)

**Comment by drupol** [comment]
@jdreesen You were right.

See: https://3v4l.org/GGDvO

There is no need to add `json_encode()`.

Merging this right now.

**Comment by drupol** [comment]
Thanks again !

**Comment by jdreesen** [comment]
Thank you too :)

**Pull request merged**
