### PR TITLE
Fix code example in README

### PR DESCRIPTION
**Pull request by jdreesen**
This PR

* [x] Fixed the code example in the readme.

### CODE REVIEW

**Comment by drupol** [comment]
Hi mate,

Thanks for your contribution (_all of them_), unfortunately, I have to decline this one. The README is good as it is and it's working perfectly well, there is no need to make that change.

**Comment by jdreesen** [comment]
No, it isn't. At least there's a syntax error in lines 60/61: https://3v4l.org/flYbb

Apart from that, the generator yields three values while the `sprintf` calls in lines 64/65 expect only two parameters: the result and the duration (in that order).

**Comment by drupol** [comment]
Oh indeed, you're perfectly right ! Sorry about that.

**Comment by drupol** [comment]
Thanks !!!

**Comment by drupol** [comment]
I updated the README again, the code example was misleading, it's now better!

**Comment by jdreesen** [comment]
But now it isn't using the fibonacci function anymore... see: https://github.com/loophp/memoize/commit/e56d6724f9dc46e22be7e9bcb6c2d1792d894125#r46031564

**Comment by drupol** [comment]
Looks like I'm working too late, I'll fix this tomorrow! Thanks!

**Pull request merged**
